### PR TITLE
Added missing libraries for WS3.0 terrain loader.

### PR DESCRIPTION
**Pull request by fdalvi**
The serialization libraries were not built earlier, hence causing
osgTerrain to fail at loading WS3.0 terrain files. This commit fixes by
building the serializer and associated libraries.

### CODE REVIEW

**Comment by fdalvi** [comment]
FYI, just enabling osgWrappers/serializers leads to the following compilation errors:

```
ld: library not found for -losgUI
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/osgPlugins/osgdb_serializers_osgui.dylib] Error 1
make[1]: *** [src/osgWrappers/serializers/osgUI/CMakeFiles/osgdb_serializers_osgui.dir/all] Error 2

ld: library not found for -losgManipulator
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/osgPlugins/osgdb_serializers_osgmanipulator.dylib] Error 1
make[1]: *** [src/osgWrappers/serializers/osgManipulator/CMakeFiles/osgdb_serializers_osgmanipulator.dir/all] Error 2

ld: library not found for -losgShadow
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/osgPlugins/osgdb_serializers_osgshadow.dylib] Error 1
make[1]: *** [src/osgWrappers/serializers/osgShadow/CMakeFiles/osgdb_serializers_osgshadow.dir/all] Error 2

ld: library not found for -losgVolume
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/osgPlugins/osgdb_serializers_osgvolume.dylib] Error 1
make[1]: *** [src/osgWrappers/serializers/osgVolume/CMakeFiles/osgdb_serializers_osgvolume.dir/all] Error 2

ld: library not found for -losgAnimation
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/osgPlugins/osgdb_serializers_osganimation.dylib] Error 1
make[1]: *** [src/osgWrappers/serializers/osgAnimation/CMakeFiles/osgdb_serializers_osganimation.dir/all] Error 2
```

and hence I had to enable those as well. There might be a way to skip these additional elements however!

**Comment by zakalawe** [comment]
Yeah we'll need to only enable the serializaers we actually need: I do *not* want to enable those extra base libraries, they're just bloat for FlightGear.

**Comment by zakalawe** [comment]
Just pushed a different version of this, can you test?

**Comment by fdalvi** [comment]
Unfortunately leads to the same compilation error. However, I figured out a fix last night; will push in a bit that can avoid building the unnecessary submodules. 

BTW commit 5ee5ef4 (most likely; definitely didn't happen before it) causes a ton of `overrides a member function but is not marked 'override'` warnings (many more, this is just a sampling):


```
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:165:31: warning: 'getUserObject' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:168:30: warning: 'getNumUserObjects' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:171:30: warning: 'getUserObjectIndex' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:174:30: warning: 'getUserObjectIndex' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:180:22: warning: 'setDescriptions' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:183:34: warning: 'getDescriptions' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:186:40: warning: 'getDescriptions' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:189:30: warning: 'getNumDescriptions' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:192:22: warning: 'addDescription' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:46:27: warning: 'asCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:47:33: warning: 'asCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:49:33: warning: 'asCallbackObject' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:50:39: warning: 'asCallbackObject' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:170:29: warning: 'asCallbackObject' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:171:35: warning: 'asCallbackObject' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:174:10: warning: 'run' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:253:31: warning: 'asNodeCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:254:37: warning: 'asNodeCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:257:22: warning: 'run' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:282:41: warning: 'asStateAttributeCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:283:47: warning: 'asStateAttributeCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:286:22: warning: 'run' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:307:30: warning: 'asUniformCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:308:36: warning: 'asUniformCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:311:18: warning: 'run' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:334:37: warning: 'asDrawableUpdateCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:335:43: warning: 'asDrawableUpdateCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:338:18: warning: 'run' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:356:36: warning: 'asDrawableEventCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:357:42: warning: 'asDrawableEventCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:360:18: warning: 'run' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:377:35: warning: 'asDrawableCullCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:378:41: warning: 'asDrawableCullCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Shader:193:22: warning: 'resizeGLObjectBuffers' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Shader:198:14: warning: 'releaseGLObjects' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Shader:335:22: warning: 'resizeGLObjectBuffers' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Shader:336:22: warning: 'releaseGLObjects' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/BufferObject:723:22: warning: 'resizeGLObjectBuffers' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Uniform:559:26: warning: 'asUniform' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Uniform:563:32: warning: 'asUniform' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Uniform:573:22: warning: 'setName' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/StateSet:456:26: warning: 'run' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/ValueObject:78:30: warning: 'asValueObject' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/ValueObject:82:36: warning: 'asValueObject' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/NodeVisitor:115:30: warning: 'asNodeVisitor' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/NodeVisitor:119:36: warning: 'asNodeVisitor' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/ShaderComposer:43:22: warning: 'releaseGLObjects' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Camera:619:26: warning: 'resizeGLObjectBuffers' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Camera:628:26: warning: 'releaseGLObjects' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/View:164:22: warning: 'resizeGLObjectBuffers' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/View:165:22: warning: 'releaseGLObjects' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:132:22: warning: 'setThreadSafeRefUnref' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:140:22: warning: 'setUserData' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:146:29: warning: 'getUserData' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:149:35: warning: 'getUserData' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:152:30: warning: 'addUserObject' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:155:22: warning: 'setUserObject' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:158:22: warning: 'removeUserObject' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:162:25: warning: 'getUserObject' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:165:31: warning: 'getUserObject' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:168:30: warning: 'getNumUserObjects' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:171:30: warning: 'getUserObjectIndex' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:174:30: warning: 'getUserObjectIndex' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:180:22: warning: 'setDescriptions' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:183:34: warning: 'getDescriptions' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:186:40: warning: 'getDescriptions' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:189:30: warning: 'getNumDescriptions' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/UserDataContainer:192:22: warning: 'addDescription' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:46:27: warning: 'asCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:47:33: warning: 'asCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:49:33: warning: 'asCallbackObject' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:50:39: warning: 'asCallbackObject' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:170:29: warning: 'asCallbackObject' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:171:35: warning: 'asCallbackObject' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:174:10: warning: 'run' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:253:31: warning: 'asNodeCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:254:37: warning: 'asNodeCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:257:22: warning: 'run' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:282:41: warning: 'asStateAttributeCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:283:47: warning: 'asStateAttributeCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:286:22: warning: 'run' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:307:30: warning: 'asUniformCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:308:36: warning: 'asUniformCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:311:18: warning: 'run' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:334:37: warning: 'asDrawableUpdateCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:335:43: warning: 'asDrawableUpdateCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:338:18: warning: 'run' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:356:36: warning: 'asDrawableEventCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:357:42: warning: 'asDrawableEventCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:360:18: warning: 'run' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:377:35: warning: 'asDrawableCullCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Callback:378:41: warning: 'asDrawableCullCallback' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Shader:193:22: warning: 'resizeGLObjectBuffers' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Shader:198:14: warning: 'releaseGLObjects' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Shader:335:22: warning: 'resizeGLObjectBuffers' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Shader:336:22: warning: 'releaseGLObjects' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/BufferObject:723:22: warning: 'resizeGLObjectBuffers' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Uniform:559:26: warning: 'asUniform' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Uniform:563:32: warning: 'asUniform' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Uniform:573:22: warning: 'setName' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/StateSet:456:26: warning: 'run' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/ValueObject:78:30: warning: 'asValueObject' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/ValueObject:82:36: warning: 'asValueObject' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/NodeVisitor:115:30: warning: 'asNodeVisitor' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/NodeVisitor:119:36: warning: 'asNodeVisitor' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/ShaderComposer:43:22: warning: 'releaseGLObjects' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Camera:619:26: warning: 'resizeGLObjectBuffers' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/Camera:628:26: warning: 'releaseGLObjects' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/View:164:22: warning: 'resizeGLObjectBuffers' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/View:165:22: warning: 'releaseGLObjects' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/FrameBufferObject:153:22: warning: 'resizeGLObjectBuffers' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
.../flightgear/src/osg-mine-36/include/osg/FrameBufferObject:158:22: warning: 'releaseGLObjects' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
```

**Comment by fdalvi** [comment]
Rebased on current branch and pushed, these changes successfully build and the terrain loads on my machine, hopefully without the extra bloat.

**Comment by zakalawe** [comment]
I'm a bit confused: your patch and mine look basically identical?! What difference between them am I missing?

The patch for the overrides, I added because since about six months, when building FG/SG, XCode complains about missing 'override' in the virtual methods inside the OSG META_ macro. So for me the patch reduces warnings when compiling SG+FG, and I'm not so worried about the ones building OSG itself. Unfortunately there is no good half-way solution here, because Winconsistent-missing-override wants /all/ virtuals in a class to use override, or not.

**Comment by fdalvi** [comment]
I think its because you were modifying the CMake file in the deprecated wrappers folder (which are commented in the main Cmake file already), and not the one that was actually being used.

**Comment by zakalawe** [comment]
Okay, I'm confused for sure, since I thought it *was* the wrappers we needed to enable with your patch. Ah but now I see, I had the wrong subdirectory open in my editor, so yeah I changed the deprecated ones, not the 'serializers' one. Okay, it makes sense at least.

What about the overrides warnings? Do you think it's worth doing anything or just accept the warnings? (

**Comment by fdalvi** [comment]
To be honest I don't have enough experience with C/C++ projects/compilers etc to make an educated judgement on whether or not the override warnings change is worth it. What you say does make sense, making FG+SG compilation cleaner should be more important than a dependency like OSG, especially since its done at a much higher frequency. Just FYI though, there are _a lot_ of warnings in the OSG compilation now, so that might be the only downside.=

**Comment by zakalawe** [comment]
I've pushed a tweaked version to my branch, give it a shot? I've also disabled the warning about inconsistent overrides when building OSG, so that we can keep the check in SG+FG where it's more valuable to us.

**Comment by fdalvi** [comment]
Works as expected!

**Comment by zakalawe** [comment]
Okay, great : thanks for figuring this one.

**Comment by fdalvi** [comment]
Happy to help!

**Pull request closed without merging**
